# Server
server.port=8080

# JPA properties
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fooddelivery;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# JWT properties (Base64-encoded 64-byte key)
keg.app.jwtSecret=5R+RzG5RCfdj8o19LxXRj6ff432iP5rwqEr4OCBdCckjtQxSII45DgtOXu2yjgKNPx/KE45zdkBXc2qN3GIhhQ==
keg.app.jwtExpirationMs=86400000

# Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=temp@gmail.com
spring.mail.password=temp
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
